Document: platon-all
Title: Debian platon-all Manual
Author: <insert document author here>
Abstract: This manual describes what platon-all is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/platon-all/platon-all.sgml.gz

Format: postscript
Files: /usr/share/doc/platon-all/platon-all.ps.gz

Format: text
Files: /usr/share/doc/platon-all/platon-all.text.gz

Format: HTML
Index: /usr/share/doc/platon-all/html/index.html
Files: /usr/share/doc/platon-all/html/*.html
